### ISSUE TITLE
time-stats: Use label match as bar title

### ISSUE THREAD

**Issue by jayvdb** [HewlettPackard/yoda#4] opened 2018-08-12 06:34 UTC
@coala uses labels like `type/*` , `difficulty/*`, `size/*`.

When I do a time-stats.html , the prefixes are shown in the bar titles.

When I use a regex like `^difficulty/(.*)$`, I would expect that only the part after the `/` would be the bar title.

https://hewlettpackard.github.io/yoda/yoda-time-stats.html?owner=coala&repolist=coala,coala-bears,coala-quickstart,coala-vs-code,community,corobo,gh-board&startdate=2018-04-01&labelsplit=%5Edifficulty/(.*)$&title=Closed%20issues%20during%20GSoC%20by%20difficulty&count=closed&draw=true

**Comment by jens-markussen** [comment] 2018-10-05 11:56
Sorry for not responding earlier. Somehow E-mail notifications went to my spam folder. Will consider and respond soon.

**Comment by jens-markussen** [comment] 2018-10-08 11:37
Hi @jayvdb. Will the label split field is working as intended. It selects the relevant labels using the regular expression. Your issue here is that the labels are quite long, and you would like to use only part of them for the presentation part.

I'll add labels matching an Enhancement request, and we will consider for upcoming Yoda 2 release at medium priority.

**Comment by jens-markussen** [comment] 2018-10-08 13:16
Ok, we decided to have a quick look at this one in detail. It turns out to be not so difficult to support positional parameter 1 in the RegExp as the legend text.

Try again. Your `^difficulty/(.*)$` example should work.

If succesfully tested, we can close this one.

**Comment by jens-markussen** [comment] 2018-10-09 07:38
See https://hewlettpackard.github.io/yoda/yoda-time-stats.html?owner=hewlettpackard&repolist=yoda-demo&labelsplit=^difficulty/(.*)$&other=&draw=true
showing this works. Closing isssue.

![image](https://user-images.githubusercontent.com/35253007/46653683-02b20c00-cba7-11e8-98e2-e34e83f96785.png)

**Closed by jens-markussen** 2018-10-09 07:38 UTC
Labels: S3 - Medium, T2 - Enhancement
